version: "1.0"

services:
  voz-a-texto:
    build: .
    container_name: VozTexto
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - .env
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./data:/app/data
    restart: unless-stopped